# Hugo site configuration
baseURL = "https://hanbinzheng.github.io/"
languageCode = "en-us"
title = "Hanbin Zheng"
theme = "PaperMod"
enableRSS = true

# ----------------------------
# 顶层 params
# ----------------------------
[params]
  # Profile 模式
  [params.profileMode]
    enabled = true
    title = "Hanbin Zheng"
    subtitle = "A rough timber, unsuitable for carving"
    imageUrl = "images/avatar.png"
    imageWidth = 180
    imageHeight = 180

    [[params.profileMode.buttons]]
    name = "About"
    url = "/about"

    [[params.profileMode.buttons]]
    name = "Academic"
    url = "/academic"

    [[params.profileMode.buttons]]
    name = "Blog"
    url = "/blog"

    [[params.profileMode.buttons]]
    name = "Else"
    url = "/else"

  # PaperMod 相关
  [params.paper]
    highlightStyle = "github"
    lightbox = true
    themeColor = "#1a1a1a"
    ShowShareButtons = true  # 分享按钮
    ShowReadingTime = true # 阅读时间
    ShowToc = true # Table of content
    TocOpen = true # 默认开启toc
    ShowCodeCopyButtons = true   # 这里启用代码块一键复制
    ShowCodeLanguages = true     # 这里显示代码语言标签



  # Math 配置，启用 MathJax
  [params.math]
    enable = true
    # engine = "katex"  # 默认就是"katex"


# ----------------------------
# 社交链接（可选）
# ----------------------------
# [[params.socialIcons]]
# name = "github"
# url = "https://github.com/hanbinzheng"

# [[params.socialIcons]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/hanbin-zheng-aaa05b376/"

# [[params.socialIcons]]
# name = "x"
# url = "https://x.com/hanbinzheng222"


# ----------------------------
# 顶部菜单
# ----------------------------
[menu]
  [[menu.main]]
    identifier = "home page"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "academic"
    name = "Academic"
    url = "/academic"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 4

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive"
    weight = 5

  [[menu.main]]
    identifier = "else"
    name = "Else"
    url = "/else"
    weight = 6